### ISSUE TITLE
[Bug] Minecraft doesn't show / App doesn't show loading screen

### ISSUE THREAD

**Issue by xXJamieXx** [FTBTeam/FTB-App-Overwolf#1]
**App Version:**
App: Closed Beta

**UI Version:**
UI: Closed Beta

**Log Files:**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs
https://pste.ch/qesanujonu

**Describe the bug**
I click play on a modpack within the FTB App, it will load the Minecraft launcher and then it will automatically click play and begin loading. Once that's done it attempts to launch Minecraft itself, the Java process will begin to run based on task manager however it doesn't show up and there's no indication of any loading other than the modpack log files themselves. I assume this is the newly announced feature where it is supposed to show the loading process within the app however that doesn't seem to be happening. Only once the modpack has fully loaded and the title screen is showing will the Minecraft window then show.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open up the Closed Beta version of the app through Overwolf.
2. Click play on any installed modpack.
3. Let the Minecraft launcher load up Minecraft.
4. See that Minecraft itself doesn't launch but shows the Java process in task manager.

**Expected behaviour**
It should launch some sort of loading screen, either Minecraft itself or a view within the FTB app.

**Screenshots**
![image](https://user-images.githubusercontent.com/11248045/98296977-a4d19780-1fab-11eb-942c-91c5b43038a7.png)

**Additional context**

**Comment by ThePaul-T** [comment]
I believe we have a fix for this already. The progress screen does not always show, rollouts are staggered so you'll get an update soon I hope. 

Minecraft will still load as expected.

**Comment by xXJamieXx** [comment]
Perfect, thank you. I'll look out for the update and see if its fixed :)

**Comment by ThePaul-T** [comment]
I can see the update has passed QA and is being rolled out, approximately 50% of people have it thus far, just checking to see if it has made it to you?

**Comment by xXJamieXx** [comment]
According to the Overwolf client library the FTB App is current 1.0.1. Wasn't aware of this display last night so not sure what the version was then but on this version I'm still experiencing the same problem, but as I said I'm not sure if it updated or not.

**Comment by ThePaul-T** [comment]
Would've been 1.0.0 last night, @Rushmead can take a look now we know you're on the latest.

**Comment by xXJamieXx** [comment]
I apologise, it does seem to be working now. Didn't seem to work the first time I launched this version of the app but now does seem to be working for every Minecraft launch.
