### ISSUE TITLE
[Bug] Loading 1.12 and 1.15+ packs (inconsistent user experience)

### ISSUE THREAD

**Issue by MrGREGhimself** [FTBTeam/FTB-App-Overwolf#10]
**App Version:**
App: Closed Beta

**UI Version:**
UI: Closed Beta

**Log Files:**
https://pste.ch/wigureqori

**Describe the bug**
When loading 1.12 packs the loading screen is replaced by the "in-app" progress bars. This is not the case for 1.15 and 1.16 packs were starting the pack loads 'FML window' to show loading progress

**To Reproduce**
Steps to reproduce the behaviour:
1. Start any 1.12 pack
2. Start any 1.15 or 1.16 pack 
3. Compare results

**Expected behaviour**
Consistent pack loading to be displayed in FTB app.

**Comment by Rushmead** [comment]
This is fixed in the next update, we just needed some more time to get the mod that does the loading screen complete.

**Comment by Rushmead** [comment]
This has been fixed in the latest 1.0.3 update.
