### ISSUE TITLE
[Bug] Choose Version of pack

### ISSUE THREAD

**Issue by manmaed** [FTBTeam/FTB-App-Overwolf#12]
**App Version:**
App Version: 202011061900-e9e8f764e1-prototyping 

**UI Version:**
UI: b65d0614 

**Log Files:**
https://pste.ch/hadijikodo
https://ss1.manmaed.net/1604778523.mp4

**Describe the bug**
When installing an new instance of a mod pack versoin window closes before you can choose what version to install

**To Reproduce**
Steps to reproduce the behaviour:
See Video

**Expected behaviour**
For the window not to close

**Screenshots**
See Video

**Additional context**

**Comment by Rushmead** [comment]
I can't re-create this issue, please try updating to the latest version of the app and trying again.

**Comment by manmaed** [comment]
***Update***

**App Version:**
App Version: 202011112311-3b21e768fd-prototyping 

**UI Version:**
UI Version: 9adb7070 


**Additional context**
Only Seems to happen on the browse page after searching for a pack and only happens when first clicking Get

**Comment by Quetzi** [comment]
This appears to be fixed now
