### ISSUE TITLE
[Bug] Unable to play packs

### ISSUE THREAD

**Issue by Temmiedahoovy** [FTBTeam/FTB-App-Overwolf#13]
**App Version:**
App: 202011061900-e9e8f764e1-prototyping

**UI Version:**
UI: b65do164

**Log Files:**
https://pste.ch/ufogotosey

**Describe the bug**
Clicking "play" in the app does nothing

**To Reproduce**
Steps to reproduce the behaviour:
1. Fresh install
2. Go to Featured packs and install any pack
3. Go to "Home" or "My Modpacks"
4. Click "Play" on any modpack

**Expected behaviour**
A loading screen or launcher showing up

**Screenshots**
N/A

**Additional context**
I uninstalled all previous FTB apps from my computer and reinstalled this one

**Comment by Gaz492** [comment]
Could you go to C:\Users\<your name> and delete the .ftba folder then try again?
If it still doesn't work can you upload a new log.

**Comment by Temmiedahoovy** [comment]
It still doesn't work
https://pste.ch/yabiboqomu

**Comment by Inki-sudo** [comment]
I am also having this issue ever since FTB updated and added Overwolf. It is not even letting me press play, and additionally, I can occasionally load the minecraft launcher but it only shows me a gray screen.

**Comment by amsolano426** [comment]
I noticed something with Overwolf...after uninstalling, I ran through the registry and found several places where there were "\\" versus "\" to show directory for file locations.  Would that cause issues on overwolf not allowing FTB App not to start???  Inquiry minds want to know... :wink:

**Comment by HalloweenTerror** [comment]
i have this same issue. the first time it worked for like 2min and then stopped and said unable to connect. now when i push play nothing opens anymore, and i cant figure out how to connect my minecraft account to my ftb account.

**Comment by MichaelHillcox** [comment]
If anyone can confirm this is still an issue, please reopen this issue report
