### ISSUE TITLE
[Bug] No content on Discover page

### ISSUE THREAD

**Issue by Sunekaer** [FTBTeam/FTB-App-Overwolf#14]
**App Version:**
App: 202011062115-e9e8f764e1-prototyping

**UI Version:**
UI: fb2a997f

**Log Files:**
https://pste.ch/oriqodoyat

**Describe the bug**
![image](https://user-images.githubusercontent.com/18720460/98519121-9e277680-2270-11eb-8226-7f3001221f58.png)

**To Reproduce**
Steps to reproduce the behaviour:
Open the app and go to Discover.

**Expected behaviour**
To show some  of the packs with links for discover

**Comment by Gaz492** [comment]
This issue has now been resolved
