### ISSUE TITLE
[Bug] Ad covers modpack loading information

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-App-Overwolf#15]
**App Version:**
App: 202011062115-e9e8f764e1-prototyping

**UI Version:**
UI: fb2a997f

**Log Files:**
https://pste.ch/oculefegev

**Describe the bug**
Ad covers modpack loading information

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the app with default window size
2. Launch a modpack
3. See error

**Expected behaviour**
For the loading text to be lower

**Screenshots**
With default window size:
![](https://i.latvian.dev/pc/2020-11-10_13.46.05.png)
Maximized window size:
![](https://i.latvian.dev/pc/2020-11-10_13.46.14.png)

**Comment by LatvianModder** [comment]
Sidenote: would be great if I could copy app/ui versions, or even better, if there was a Generate Template button. Unless I completely missed where to get those from

**Comment by Gaz492** [comment]
> 
> 
> Sidenote: would be great if I could copy app/ui versions, or even better, if there was a Generate Template button. Unless I completely missed where to get those from

The copy versions thing has been added in a prototype version of the app, the changes just need to be merged in.
Not sure what you mean by Generate Template button

**Comment by LatvianModder** [comment]
Button that instead of copying IDs it would just copy you a pre-written github issue template:

```
App Version:
App: <version>

UI Version:
UI: <version>

Log Files:
https://pste.ch/<log url here>

...
```
