### ISSUE TITLE
Updating FTB Interactions, then freezes

### ISSUE THREAD

**Issue by DJDrWright** [FTBTeam/FTB-App-Overwolf#18]
I updated to newest version of Interactions, the app gathers data, forge information, downloads .jar files, Post-install tasks, then reads finished but everything is greyed out and nothing I click on does anything. I have to x out of the app. When I restart the app Interactions is not updated. App version: 202011272035-6c3f7406fc-prototyping UI version: b78fcbfa

**Comment by Quetzi** [comment]
Could you please provide your logs
