### ISSUE TITLE
[Bug] "Give Feedback" icon - points to non-FTB/Overwolf Github issues page

### ISSUE THREAD

**Issue by MrGREGhimself** [FTBTeam/FTB-App-Overwolf#2]
**App Version:**
App: Closed Beta

**UI Version:**
UI: Closed Beta

**Describe the bug**
When you click on the double-cloud "Give feedback" icon, it takes you to FTB App issues page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Closed Beta FTB/Overwolf app
2. Click on 'Give feedback icon'
3. See the result.

**Expected behaviour**
Clicking on the icon should take you to FTB-App-Overwolf Github

**Comment by Gaz492** [comment]
Fixed in next version
