### ISSUE TITLE
Stoneblock 2 Dedi Server issue

### ISSUE THREAD

**Issue by kooky112** [FTBTeam/FTB-App-Overwolf#22]
**App Version:**
App:  Stoneblock 2 1.21.1

**UI Version:**
UI: 

**Log Files:**
**REQUIRED**
https://pste.ch/ridubevovu

**Describe the bug**
I'm not sure where else I can put this since it seems the stoneblock 2 people aren't paying attention to their issues. I can play the modpack fine in solo mode and in a LAN with my husband. The issue is when we try to play on our dedicated server we have one VERY weird issue where if we dig down, then go down the hole the game crashes, or if we jump the game crashes. Basically, we have to leave whatever block level we are on for the game to crash. And the game itself doesnt crash and the server doesn't fully crash either, the network jut boots me.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to our dedicated server at kooky112.ddns.net
2. join in and wait for game to load
3. jump using space, or dig down one block then step into the new hole
4. profit

**Expected behaviour**
You'll get booted from the server

**Additional context**
I don't pay for this server, I own the physical machine and I've never had a problem hosting stoneblock 2 as a dedicated server back when it was on Twitch, now that it's been moved to the FTB app, this issue exists and I don't know why.

**Comment by Quetzi** [comment]
This should be posted on the Stoneblock 2 tracker: https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues
