### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Sandman192** [FTBTeam/FTB-App-Overwolf#25]
**App Version:**
App: 202012021741-eaf41def11-debugging

**UI Version:**
UI: 9e6200dd

**Log Files:**
**REQUIRED**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs
https://pste.ch/qigocixefe

**Describe the bug**
No sound in the Discover tab and no sound in ads when downloading a mod and the speaker icon goes away when an ad plays.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
To play sounds when unmuting from speaker icon.
**Screenshots**

**Additional context**

**Comment by MichaelHillcox** [comment]
This has likely been fixed :+1:
