### ISSUE TITLE
[Bug]-Can't play Modpack

### ISSUE THREAD

**Issue by johanghostwolf** [FTBTeam/FTB-App-Overwolf#26]
**App Version:**
App: 202012021741-eaf41def11-debugging

**UI Version:**
UI: 9e6200dd

**Log Files:**
**REQUIRED**
https://pste.ch/caseqevizu

**Describe the bug**
Minecraft keeps crashing when trying to play Direwolf20 mod pack. When returning to the FTB Homepage it tells me that something went wrong with the FTB app.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the FTB app.
2. Launch the Direwolf20 Modpack
3. press play in Minecraft Launcher
4. Wait for the game to launch.
5. Minecraft says the game has crashed and the FTB app says something went wrong with the FTB app

**Expected behaviour**
The direwolf20 mod pack to launch.

**Screenshots**
Minecraft:
![image](https://user-images.githubusercontent.com/57966241/102468782-a5555780-405a-11eb-84e8-f3654ebee605.png)

**Additional context**
The FTB app doe not crash every time Minecraft Crashes.

**Comment by CSSkies** [comment]
pastebin says the forge version failed to download:
"INFO: Attempting to downloaded required files
Dec 17, 2020 10:35:29 AM net.creeperhost.creeperlauncher.CreeperLogger warning
WARNING: forge-1.16.4-35.1.13.jar error 404: Not Found!
Dec 17, 2020 10:35:29 AM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.install.tasks.DownloadTask.lambda$execute$0(DownloadTask.java:57)
Unable to download forge-1.16.4-35.1.13.jar
Dec 17, 2020 10:35:29 AM net.creeperhost.creeperlauncher.CreeperLogger warning
WARNING: asm-util-7.2.jar error 404: Not Found!"

**Comment by MichaelHillcox** [comment]
Hay, this is more likely a modpack issue, please have a look in the crash log and see if you can see what mod might be crashing the pack. If this is a app issue, try reinstalling the pack, we've had forge install issues before... Gunna close as this issue is quite old, hopefully your issue is already resolved.
