### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Max16643** [FTBTeam/FTB-App-Overwolf#27]
**App Version:**
App: 202012021741-eaf41def11-debugging

**UI Version:**
UI: 9e6200dd

**Log Files:**
**REQUIRED**
https://pste.ch/oqecesijar
Put links to your logs here  
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**
when i press play on any modpack it dosent do anything 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'browse  and download any modpack...'
2. Click on 'play '
3. nothing happens
**Expected behaviour**
A loading screen or launcher showing up

**Screenshots**
N/A
**Additional context**
just downloaded the newest version of the FTB launcher

**Comment by Alfaeddy** [comment]
https://pste.ch/idozikiquy
I'm having the same issue click play and nothing happens I've already uninstalled and reinstalled nothing changed.

**Comment by Krachwe** [comment]
I have the Same Problem

**Comment by Trigger0x10c** [comment]
Same thing. Can't play anything, even reinstalling Overwolf doesn't help.

**Comment by MichaelHillcox** [comment]
Are you on linux?

**Comment by MichaelHillcox** [comment]
Please update this issue if any of you are still having this issue :+1:
