### ISSUE TITLE
Launcher freezes at one modpack

### ISSUE THREAD

**Issue by Simpoug** [FTBTeam/FTB-App-Overwolf#28]
I have this issue where when I launch the game, the launcher starts loading in the mods and just stops loading at some mods, most commonly ender io. This usually gets solved when I reinstall the pack and restart my pc but it no longer does.

**Comment by HalloweenTerror** [comment]
i had this problem, check your drives. they can be close to full or empty your trach can, that does keep the old files and that takes up space.

**Comment by Quetzi** [comment]
Please use the issue template provided.
