### ISSUE TITLE
[Bug] Mod launcher does nothing

### ISSUE THREAD

**Issue by HalloweenTerror** [FTBTeam/FTB-App-Overwolf#29]
**App Version:**
App: 202012191727-46b0d45df5-preview

**UI Version:**
UI: 2c223e0c

**Log Files:** nothing happens
**REQUIRED**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**
the launcher does nothing for me, cant push play, cant connect Minecraft account
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...' ftb mod launcher
2. Click on '....' download mod
3. Scroll down to '....' click play
4. See error nothing happens

**Expected behaviour**
the can loads onto minecraft and the mod packs work
**Screenshots**
**Additional context**
I tried deleting and redownloading everything, or restarting my pc.

**Comment by Quetzi** [comment]
Please include the logs from your App: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Comment by MichaelHillcox** [comment]
Awaiting response
