### ISSUE TITLE
[Bug] FTB Unleashed - Optifine

### ISSUE THREAD

**Issue by CSSkies** [FTBTeam/FTB-App-Overwolf#30]
Cannot use Optifine with FTB Unleashed using the CurseForge Launcher, due to differing file structure.

The Old FTB Launcher uses a file structure having three folders inside the pack folder, including one called "minecraft" that contains all the normal things. File structure goes: "'FTB' > 'Unleashed' > 'instMods', 'minecraft', natives', and a file called versions. Optifine goes in the "instMods folder", which is where I put it in both the FTB and Curseforge Launcher, but the latter doesn't recognize it.

This also happened with the old Twitch Mods section; using Optifine on such an old version of forge might no longer be possible.

**Comment by Quetzi** [comment]
Optifine is not supported by FTB, we also do not provide support for the CurseForge App.

**Comment by CSSkies** [comment]
Oh ok, I was redirected toward here for that issue. My bad.
