### ISSUE TITLE
[Bug] Cant join Server in FTB Infinity Evolved

### ISSUE THREAD

**Issue by Chromalaun** [FTBTeam/FTB-App-Overwolf#31]
**App Version:**
App: FTB App 202012311506-9b05a8bfd7-prototyping

**UI Version:**
UI: fd9780e6

**Log Files:**
https://pste.ch/cojiqeyucu

Description: When I try to join my private FTB Infinity Evolved server (hosted on Nitrado) I get stuck in the loading screen that looks like dirt. In the server console i can see that I logged in properly and instantly logged out again. The Minecraft Launcher sends a Error Message that looks like this : "The game crashed whilst unexpected error Error: java.lang.NullPointerException: Unexpected error Exit Code: -1" Other people can join the server.

Steps to reproduce the behaviour:
1. Run FTB Infinity Evolved from the FTB App
2. Click on Multiplayer
3. Connect to the Server
4. Get stuck in the loading screen / application closes

It worked just fine and then I got kicked. Since than I cant reconect.

Iam not using Optifine or any ressource pack.

Any idea what could work to fix my problem?
Thanks!

**Comment by Quetzi** [comment]
This tracker is for the FTB App, the App is launching the game correctly you should post this issue to the packs bug tracker.
