### ISSUE TITLE
[Bug] Beta pack A

### ISSUE THREAD

**Issue by Dreazzer57** [FTBTeam/FTB-App-Overwolf#32]
**App Version:**
App: 0.167.1.4 

**UI Version:**
UI: 

**Log Files:** https://pastebin.com/PsqtgB7u
**REQUIRED**
Put links to your logs here
how to find logs: https://faq.ftb.world/books/ftb-app/page/uploading-app-logs

**Describe the bug**
installed the ftb beta pack a from curse forge, but the game won't start, only crash again and again, no matter what

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

Having a working game

**Screenshots**

**Additional context**

**Comment by Quetzi** [comment]
This tracker is for the FTB App, not the CursseForge App.
