### ISSUE TITLE
[Bug] "Loading..." message constantly displayed below Settings option

### ISSUE THREAD

**Issue by MrGREGhimself** [FTBTeam/FTB-App-Overwolf#5]
**App Version:**
App: Closed Beta

**UI Version:**
UI: Closed Beta

**Describe the bug**
A "Loading..." message with spinny dots is displayed just below Settings menu option.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open app

**Expected behaviour**
No such message is displayed

**Screenshots**
Attached
![Loading](https://user-images.githubusercontent.com/12535527/98405979-0dc91600-2065-11eb-8197-b565fc94108a.PNG)

**Additional context**
I've removed both FTB folders from AppData after uninstalling the previous app.

**Comment by Gaz492** [comment]
Please upload the logs for the app as per the issue template.
Without the logs it very difficult to track down the issue

**Comment by Gaz492** [comment]
Ive just been informed this will be fixed in the next update
