### ISSUE TITLE
[Bug]No ad showing while loading mod pack instance

### ISSUE THREAD

**Issue by memyselfandcj** [FTBTeam/FTB-App-Overwolf#7]
**App Version:**
App: closed beta

**UI Version:**
UI: closed beta

**Describe the bug**
When waiting for a mod pack to load there is no ad running.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click play on mod pack
2. wait for mod pack to load
3. No ads rolling

Expected behaviour:
Ads to run while pack is loading

ScreenShot: 
![FTBApp 11_6_2020 5_39_56 PM](https://user-images.githubusercontent.com/40968814/98421653-d011c080-2057-11eb-9007-8d68c241a4ae.png)

**Comment by Sunekaer** [comment]
log?

**Comment by memyselfandcj** [comment]
[latest.log](https://github.com/FTBTeam/FTB-App-Overwolf/files/5503946/latest.log)

**Comment by Sunekaer** [comment]
No the game log, the app log

**Comment by memyselfandcj** [comment]
Sorry...
https://pste.ch/epidayosiq

**Comment by MrGREGhimself** [comment]
Same issue on my end
![no-ad](https://user-images.githubusercontent.com/12535527/98437250-b4023380-20d8-11eb-9976-6e580379dfc0.png)
App log:
https://pste.ch/picofutusu
