### ISSUE TITLE
[Bug] Lack of tags for "Material Energy^5" pack in "more" option

### ISSUE THREAD

**Issue by MrGREGhimself** [FTBTeam/FTB-App-Overwolf#8]
**App Version:**
App: Closed Beta

**UI Version:**
UI: Closed Beta

**Log Files:**
https://pste.ch/pogegusapi

**Describe the bug**
Checking more information about the pack revealed no tags (unlike for any other pack) available in the app.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open app
2. Go to "Browse" (or search and type "Material")
3. Click on "more" next to "Material Energy^5:Entity"
4. Notice lack of tags assigned to this pack.

**Expected behaviour**
Tags assigned.

**Screenshots**
![no-tags](https://user-images.githubusercontent.com/12535527/98438274-09424300-20e1-11eb-9210-2f3d782e0d81.PNG)

**Additional context**
I've checked all other packs visible and all have at least 2 tags.

**Comment by Sunekaer** [comment]
Not a launcher issue, the pack doesnt have any tags
And its on ME5 add them ill add a few tho
