### ISSUE TITLE
[Bug] User flow in "Browse" menu.

### ISSUE THREAD

**Issue by MrGREGhimself** [FTBTeam/FTB-App-Overwolf#9]
**App Version:**
App: Closed Beta

**UI Version:**
UI: Closed Beta

**Log Files:**
https://pste.ch/gozejujoto

**Describe the bug**
In the Browse menu, there are 3 tabs available: Featured, Top Instals and Top Plays. 

In Featured: You can check more info about the pack and when clicking on "back button" (left-pointing arrow) it takes you back to the Featured tab to show all packs included in that section. (This flows as expected)

In Top Installs and Top Plays: You can check more info about the pack and when clicking on "back button" (left-pointing arrow) it takes you back to the Featured tab to show all packs included in that section. (This flows **NOT** as expected)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Browse'
2. Click on 'Top Installs' tab.
3. Click 'more' on any pack.
4. Click 'back'.

**Expected behaviour**
User flow is more consistent where clicking 'back' is going back to the same section rather than the default (Featured).

**Comment by Rushmead** [comment]
In this case, each tab is not it's own page, they are all on the same page, meaning that navigating back to the page resets the current tab. This is less of a bug and more of a feature request.

**Comment by MichaelHillcox** [comment]
This flow has now been changed so I'm gunna close this :+1:
